name: Build, Push And Deploy

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push To Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: andyrewco/portfolio

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./code
          file: ./code/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Replace $VERSION in portfolio.stack.yaml
        run: |
          export VERSION="${{ github.ref_name }}"
          sed -i "s/\$VERSION/$VERSION/g" ./iac/portfolio.stack.yaml

      - name: Configure Swarm
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            rm -f /andrewnathan/portfolio/portfolio.stack.yaml

      - name: Copy Files To Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./iac/portfolio.stack.yaml
          remote: /andrewnathan/portfolio/portfolio.stack.yaml
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          privateKey: ${{ secrets.SERVER_KEY }}

      - name: Configure Swarm
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /andrewnathan/portfolio
            docker compose -f portfolio.stack.yaml down
            docker compose -f portfolio.stack.yaml up -d
